### ISSUE TITLE
How to get the list of MRI in OASIS appear in MICCAI 2012

### ISSUE THREAD

**Issue by ZYX-MLer** [trypag/pytorch-unet-segnet#1]
hi

thank you for your great work on MRI segmentation, in you paper

Semi-supervised Learning for Segmentation Under Semantic Constraint
you side :

The OASIS dataset was used as the source of unlabelled training data for the semi-supervised experiments, excluding the subjects who also appear in MICCAI 2012.
can you shear the list of MRI in oasis appear in MICCAI 2012

thank you very much

Looking forward to your reply!

Best
zyx

**Comment by trypag** [comment]
Hi @HebutAIer ,
Sorry I missed your question, have a look at the attached file, you will find the mapping from miccai 2012 to oasis.
[MICCAI_2012_Workshop_v2.pdf](https://github.com/trypag/pytorch-unet-segnet/files/2543932/MICCAI_2012_Workshop_v2.pdf)

```python
        self.avoid_train_patients = [
            '0061', '0080', '0092', '0145', '0150', '0156', '0191', '0202',
            '0230', '0236', '0239', '0249', '0285', '0353', '0368'
        ]

        self.avoid_test_patients = [
            '0101', '0111', '0117', '0379', '0395', '0101', '0111', '0117',
            '0379', '0395', '0091', '0417', '0040', '0282', '0331', '0456',
            '0300', '0220', '0113', '0083'
        ]

        self.avoid_patients = self.avoid_train_patients + self.avoid_train_patients
```
Best

**Comment by ZYX-MLer** [comment]
Thank you very much. 😊

**Comment by ZYX-MLer** [comment]
hi @trypag 

I find the raw scans, which is named as xxx_mpr-z_anon in oasis1&2, has many noise and include other part of head such as neck and mouth, but some scans which named like  xxx_mpr_ni_anon _sbj_111 is as clear as miccai data set, which scans do you use in your paper? thank you~

**Comment by trypag** [comment]
Hi @HebutAIer,
I only use scan ending with `_mpr-1_anon.img` for the semi-supervised part. I have to say, I didn't inspect all files, some images might be noisy or even with wrong orientations. It does not seem to affect our method negatively.

**Comment by ZYX-MLer** [comment]
Thank you for your answer 😊
