### ISSUE TITLE
report some results?

### ISSUE THREAD

**Issue by TiankaiHang** [trypag/pytorch-unet-segnet#4]
Hi,
thanks for your nice and awesome work!
Will you report some number (segmentation results) on some datasets, such as some medical competition datasets or some common natural datasets (cityscapes, pascal voc 2012).

Best.

**Comment by trypag** [comment]
Hello,
Good point, that would be a nice improvement, though it's not something I
plan to do. I have moved to other projects.
Best

**Comment by TiankaiHang** [comment]
Well, thanks~
